server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: expense-service
    
  datasource:
    url: jdbc:postgresql://localhost:5332/ecospend
    username: ${DB_USER:ecospend}
    password: ${DB_PASSWORD:ecospend_dev}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
